### ISSUE TITLE
Can't find recvive file in FileExplorer on Android11

### ISSUE THREAD

**Issue by nefusmzj** [LANDrop/LANDrop#100]
LanDrop On Android11(xiaomi/10s/MIUI12.5)，Can't find recvive file in FileExplorer。 Send  a word file(docx) to mobile phone，and receive success, but can't find it in my fileExporer。 Where is the file?

thank you.

**Comment by vivadavid** [comment]
Hi, @nefusmzj !

I used the programme today for the first time and this is what I found out.

Probably for security reasons related to Android 11, your file is stored in your LANDrop folder, which isn't accessible by default.  You can access it using Amaze File Explorer, and the path is:

Android / Data / app.landrop.landrop_flutter / Files

You don't have to do this, though. If you want to copy your file to a particular folder, just go the LANDrop app and then to the Files section. Tap on the three dots and then on Share. Look for your file explorer app and then choose the destination folder.

By doing this, your file will be copied, and so you'll have to delete it from the LANDrop folder by tapping on the three dots and then on Delete.

I should open a thread to suggest a change in the behaviour of the app. It'd be nice to be able to choose (via settings) your destination folder (if allowed by Android)

**Comment by nefusmzj** [comment]
Thank, @vivadavid !
You are right, this problem only occured on Android 11. base on you suggection "Tap on the three dots and then on Share", I find there is no share option called file explorer, it can only shared with other Apps.

**Comment by vivadavid** [comment]
Hi, @nefusmzj 

It worked for me on my Xiaomi phone:: maybe your file explorer has a different name or maybe it appears at the end of the list of apps you can use on Share. It really depends on the implementation of the Share button of your Android phone.

If using the Share feature doesn't work for you, you may want to try my other alternative. The LANDrop folder isn't accessible due to security reasons, but you can get there via Amaze (by the way, the actual name is 'Amaze File Manager').

Remember that, as far as I know, if you use the Share button, you're duplicating your file, so you need to delete it in LANDrop.

Good luck!

**Comment by nefusmzj** [comment]
Thanks, @vivadavid 
Your answer was very detailed, Let me have a try。
